/*

-----------------------------------------------------------------------------------------------------------------------------------
                                               Guidelines
-----------------------------------------------------------------------------------------------------------------------------------

The provided document is a guide for the project. Follow the instructions and take the necessary steps to finish
the project in the SQL file			

-----------------------------------------------------------------------------------------------------------------------------------

                                                         Queries
                                               
-----------------------------------------------------------------------------------------------------------------------------------*/





-- 1. WRITE A QUERY TO DISPLAY CUSTOMER FULL NAME WITH THEIR TITLE (MR/MS), BOTH FIRST NAME AND LAST NAME ARE IN UPPER CASE WITH 
-- CUSTOMER EMAIL ID, CUSTOMER CREATIONDATE AND DISPLAY CUSTOMER’S CATEGORY AFTER APPLYING BELOW CATEGORIZATION RULES:
	-- i.IF CUSTOMER CREATION DATE YEAR <2005 THEN CATEGORY A
    -- ii.IF CUSTOMER CREATION DATE YEAR >=2005 AND <2011 THEN CATEGORY B
    -- iii.IF CUSTOMER CREATION DATE YEAR>= 2011 THEN CATEGORY C
    -- HINT: USE CASE STATEMENT, NO PERMANENT CHANGE IN TABLE REQUIRED. [NOTE: TABLES TO BE USED -ONLINE_CUSTOMER TABLE]
    
SELECT
    CASE 
        WHEN CUSTOMER_GENDER = 'M' THEN concat('Mr. ' , UPPER(CUSTOMER_FName) , ' ' , UPPER(CUSTOMER_LName))
        WHEN CUSTOMER_GENDER = 'F' THEN CONCAT('Ms. ' , UPPER(CUSTOMER_FName) , ' ' , UPPER(CUSTOMER_LName))
        ELSE UPPER(CUSTOMER_FName) || ' ' || UPPER(CUSTOMER_LName)
    END AS FullName,
    CUSTOMER_EMAIL,
    CUSTOMER_CREATION_DATE,
    CASE 
        WHEN EXTRACT(YEAR FROM CUSTOMER_CREATION_DATE) < 2005 THEN 'Category A'
        WHEN EXTRACT(YEAR FROM CUSTOMER_CREATION_DATE) >= 2005 AND EXTRACT(YEAR FROM CUSTOMER_CREATION_DATE) < 2011 THEN 'Category B'
        WHEN EXTRACT(YEAR FROM CUSTOMER_CREATION_DATE) >= 2011 THEN 'Category C'
    END AS Category
FROM 
    ORDERS.ONLINE_CUSTOMER;





-- 2. WRITE A QUERY TO DISPLAY THE FOLLOWING INFORMATION FOR THE PRODUCTS, WHICH HAVE NOT BEEN SOLD:  PRODUCT_ID, PRODUCT_DESC, 
-- PRODUCT_QUANTITY_AVAIL, PRODUCT_PRICE,INVENTORY VALUES(PRODUCT_QUANTITY_AVAIL*PRODUCT_PRICE), NEW_PRICE AFTER APPLYING DISCOUNT 
-- AS PER BELOW CRITERIA. SORT THE OUTPUT WITH RESPECT TO DECREASING VALUE OF INVENTORY_VALUE.
	-- i.IF PRODUCT PRICE > 20,000 THEN APPLY 20% DISCOUNT
    -- ii.IF PRODUCT PRICE > 10,000 THEN APPLY 15% DISCOUNT
    -- iii.IF PRODUCT PRICE =< 10,000 THEN APPLY 10% DISCOUNT
    -- HINT: USE CASE STATEMENT, NO PERMANENT CHANGE IN TABLE REQUIRED. [NOTE: TABLES TO BE USED -PRODUCT, ORDER_ITEMS TABLE] 
  
SELECT 
    p.PRODUCT_ID,
    p.PRODUCT_DESC,
    p.PRODUCT_QUANTITY_AVAIL,
    p.PRODUCT_PRICE,
    (p.PRODUCT_QUANTITY_AVAIL * p.PRODUCT_PRICE) AS INVENTORY_VALUE,
    CASE
        WHEN p.PRODUCT_PRICE > 20000 THEN p.PRODUCT_PRICE * 0.80
        WHEN p.PRODUCT_PRICE > 10000 THEN p.PRODUCT_PRICE * 0.85
        ELSE p.PRODUCT_PRICE * 0.90
    END AS NEW_PRICE
FROM 
    PRODUCT p
LEFT JOIN 
    ORDER_ITEMS oi ON p.PRODUCT_ID = oi.PRODUCT_ID
WHERE 
    oi.PRODUCT_ID IS NULL
ORDER BY 
    INVENTORY_VALUE DESC;




-- 3. WRITE A QUERY TO DISPLAY PRODUCT_CLASS_CODE, PRODUCT_CLASS_DESCRIPTION, COUNT OF PRODUCT TYPE IN EACH PRODUCT CLASS, 
-- INVENTORY VALUE (P.PRODUCT_QUANTITY_AVAIL*P.PRODUCT_PRICE). INFORMATION SHOULD BE DISPLAYED FOR ONLY THOSE PRODUCT_CLASS_CODE 
-- WHICH HAVE MORE THAN 1,00,000 INVENTORY VALUE. SORT THE OUTPUT WITH RESPECT TO DECREASING VALUE OF INVENTORY_VALUE.
	-- [NOTE: TABLES TO BE USED -PRODUCT, PRODUCT_CLASS]
    SELECT 
    pc.PRODUCT_CLASS_CODE, 
    pc.PRODUCT_CLASS_DESC, 
    COUNT(p.PRODUCT_CLASS_CODE) AS PRODUCT_TYPE_COUNT,
    SUM(p.PRODUCT_QUANTITY_AVAIL * p.PRODUCT_PRICE) AS INVENTORY_VALUE
FROM 
    PRODUCT p
JOIN 
    PRODUCT_CLASS pc
ON 
    p.PRODUCT_CLASS_CODE = pc.PRODUCT_CLASS_CODE
GROUP BY 
    pc.PRODUCT_CLASS_CODE, 
    pc.PRODUCT_CLASS_DESC
HAVING 
    SUM(p.PRODUCT_QUANTITY_AVAIL * p.PRODUCT_PRICE) > 100000
ORDER BY 
    INVENTORY_VALUE DESC;

    
    
    


-- 4. WRITE A QUERY TO DISPLAY CUSTOMER_ID, FULL NAME, CUSTOMER_EMAIL, CUSTOMER_PHONE AND COUNTRY OF CUSTOMERS WHO HAVE CANCELLED 
-- ALL THE ORDERS PLACED BY THEM(USE SUB-QUERY)
	-- [NOTE: TABLES TO BE USED - ONLINE_CUSTOMER, ADDRESSS, ORDER_HEADER]


SELECT oc.CUSTOMER_ID,
       CONCAT(oc.CUSTOMER_FNAME, ' ', oc.CUSTOMER_LNAME) AS FULL_NAME, 
       oc.CUSTOMER_EMAIL, 
       oc.CUSTOMER_PHONE, 
       a.COUNTRY
FROM ONLINE_CUSTOMER oc
JOIN ADDRESS a ON oc.ADDRESS_ID = a.ADDRESS_ID
WHERE oc.CUSTOMER_ID IN (
    SELECT oh.CUSTOMER_ID
    FROM ORDER_HEADER oh
    WHERE oh.ORDER_STATUS = 'cancelled'
    GROUP BY oh.CUSTOMER_ID
    HAVING COUNT(*) = (SELECT COUNT(*) FROM ORDER_HEADER WHERE CUSTOMER_ID = oh.CUSTOMER_ID)
);






        
-- 5. WRITE A QUERY TO DISPLAY SHIPPER NAME, CITY TO WHICH IT IS CATERING, NUMBER OF CUSTOMER CATERED BY THE SHIPPER IN THE CITY AND 
-- NUMBER OF CONSIGNMENTS DELIVERED TO THAT CITY FOR SHIPPER DHL(9 ROWS)
	-- [NOTE: TABLES TO BE USED -SHIPPER, ONLINE_CUSTOMER, ADDRESSS, ORDER_HEADER]
SELECT 
    s.SHIPPER_NAME, 
    a.CITY, 
    COUNT(DISTINCT c.CUSTOMER_ID) AS NUMBER_OF_CUSTOMERS,
    COUNT(o.ORDER_ID) AS NUMBER_OF_CONSIGNMENTS
FROM 
    SHIPPER s
JOIN 
    ORDER_HEADER o ON s.SHIPPER_ID = o.SHIPPER_ID
JOIN 
    ONLINE_CUSTOMER c ON o.CUSTOMER_ID = c.CUSTOMER_ID
JOIN 
    ADDRESS a ON c.ADDRESS_ID = a.ADDRESS_ID
WHERE 
    s.SHIPPER_NAME = 'DHL'
GROUP BY 
    s.SHIPPER_NAME, 
    a.CITY
LIMIT 9;

    

    


-- 6. WRITE A QUERY TO DISPLAY CUSTOMER ID, CUSTOMER FULL NAME, TOTAL QUANTITY AND TOTAL VALUE (QUANTITY*PRICE) SHIPPED WHERE MODE 
-- OF PAYMENT IS CASH AND CUSTOMER LAST NAME STARTS WITH 'G'
	-- [NOTE: TABLES TO BE USED -ONLINE_CUSTOMER, ORDER_ITEMS, PRODUCT, ORDER_HEADER]
    
   SELECT oc.CUSTOMER_ID,
       CONCAT(oc.CUSTOMER_FNAME, ' ', oc.CUSTOMER_LNAME) AS CUSTOMER_FULL_NAME,
       SUM(oi.PRODUCT_QUANTITY) AS TOTAL_QUANTITY,
       SUM(oi.PRODUCT_QUANTITY * p.PRODUCT_PRICE) AS TOTAL_VALUE_SHIPPED
FROM ONLINE_CUSTOMER oc
JOIN ORDER_HEADER oh ON oc.CUSTOMER_ID = oh.CUSTOMER_ID
JOIN ORDER_ITEMS oi ON oh.ORDER_ID = oi.ORDER_ID
JOIN PRODUCT p ON oi.PRODUCT_ID = p.PRODUCT_ID
WHERE oh.PAYMENT_MODE = 'CASH'
  AND oc.CUSTOMER_LNAME LIKE 'G%'
GROUP BY oc.CUSTOMER_ID, oc.CUSTOMER_FNAME, oc.CUSTOMER_LNAME;





    
-- 7. WRITE A QUERY TO DISPLAY ORDER_ID AND VOLUME OF BIGGEST ORDER (IN TERMS OF VOLUME) THAT CAN FIT IN CARTON ID 10  
	-- [NOTE: TABLES TO BE USED -CARTON, ORDER_ITEMS, PRODUCT]
    
SELECT 
    oi.ORDER_ID,
    SUM(p.LEN * p.WIDTH * p.HEIGHT * oi.PRODUCT_QUANTITY) AS TOTAL_VOLUME
FROM 
    ORDER_ITEMS oi
JOIN 
    PRODUCT p ON oi.PRODUCT_ID = p.PRODUCT_ID
JOIN 
    (SELECT CARTON_ID, LEN * WIDTH * HEIGHT AS VOLUME FROM CARTON WHERE CARTON_ID = 10) c ON c.CARTON_ID = 10
GROUP BY 
    oi.ORDER_ID
HAVING 
    TOTAL_VOLUME <= (SELECT LEN * WIDTH * HEIGHT FROM CARTON WHERE CARTON_ID = 10)
ORDER BY 
    TOTAL_VOLUME 
LIMIT 1;



-- 8. WRITE A QUERY TO DISPLAY PRODUCT_ID, PRODUCT_DESC, PRODUCT_QUANTITY_AVAIL, QUANTITY SOLD, AND SHOW INVENTORY STATUS OF 
-- PRODUCTS AS BELOW AS PER BELOW CONDITION:
	-- A.FOR ELECTRONICS AND COMPUTER CATEGORIES, 
		-- i.IF SALES TILL DATE IS ZERO THEN SHOW 'NO SALES IN PAST, GIVE DISCOUNT TO REDUCE INVENTORY',
        -- ii.IF INVENTORY QUANTITY IS LESS THAN 10% OF QUANTITY SOLD, SHOW 'LOW INVENTORY, NEED TO ADD INVENTORY', 
        -- iii.IF INVENTORY QUANTITY IS LESS THAN 50% OF QUANTITY SOLD, SHOW 'MEDIUM INVENTORY, NEED TO ADD SOME INVENTORY', 
        -- iv.IF INVENTORY QUANTITY IS MORE OR EQUAL TO 50% OF QUANTITY SOLD, SHOW 'SUFFICIENT INVENTORY'
	-- B.FOR MOBILES AND WATCHES CATEGORIES, 
		-- i.IF SALES TILL DATE IS ZERO THEN SHOW 'NO SALES IN PAST, GIVE DISCOUNT TO REDUCE INVENTORY', 
        -- ii.IF INVENTORY QUANTITY IS LESS THAN 20% OF QUANTITY SOLD, SHOW 'LOW INVENTORY, NEED TO ADD INVENTORY',  
        -- iii.IF INVENTORY QUANTITY IS LESS THAN 60% OF QUANTITY SOLD, SHOW 'MEDIUM INVENTORY, NEED TO ADD SOME INVENTORY', 
        -- iv.IF INVENTORY QUANTITY IS MORE OR EQUAL TO 60% OF QUANTITY SOLD, SHOW 'SUFFICIENT INVENTORY'
	-- C.REST OF THE CATEGORIES, 
		-- i.IF SALES TILL DATE IS ZERO THEN SHOW 'NO SALES IN PAST, GIVE DISCOUNT TO REDUCE INVENTORY', 
        -- ii.IF INVENTORY QUANTITY IS LESS THAN 30% OF QUANTITY SOLD, SHOW 'LOW INVENTORY, NEED TO ADD INVENTORY',  
        -- iii.IF INVENTORY QUANTITY IS LESS THAN 70% OF QUANTITY SOLD, SHOW 'MEDIUM INVENTORY, NEED TO ADD SOME INVENTORY', 
        -- iv. IF INVENTORY QUANTITY IS MORE OR EQUAL TO 70% OF QUANTITY SOLD, SHOW 'SUFFICIENT INVENTORY'
        
			-- [NOTE: TABLES TO BE USED -PRODUCT, PRODUCT_CLASS, ORDER_ITEMS] (USE SUB-QUERY)
            
 SELECT 
    p.PRODUCT_ID,
    p.PRODUCT_DESC,
    p.PRODUCT_QUANTITY_AVAIL,
    COALESCE(s.QUANTITY_SOLD, 0) AS QUANTITY_SOLD,
    CASE
        WHEN pc.PRODUCT_CLASS_DESC IN ('Electronics', 'Computer') THEN
            CASE
                WHEN COALESCE(s.QUANTITY_SOLD, 0) = 0 THEN 'NO SALES IN PAST, GIVE DISCOUNT TO REDUCE INVENTORY'
                WHEN p.PRODUCT_QUANTITY_AVAIL < 0.1 * COALESCE(s.QUANTITY_SOLD, 0) THEN 'LOW INVENTORY, NEED TO ADD INVENTORY'
                WHEN p.PRODUCT_QUANTITY_AVAIL < 0.5 * COALESCE(s.QUANTITY_SOLD, 0) THEN 'MEDIUM INVENTORY, NEED TO ADD SOME INVENTORY'
                ELSE 'SUFFICIENT INVENTORY'
            END
        WHEN pc.PRODUCT_CLASS_DESC IN ('Mobiles', 'Watches') THEN
            CASE
                WHEN COALESCE(s.QUANTITY_SOLD, 0) = 0 THEN 'NO SALES IN PAST, GIVE DISCOUNT TO REDUCE INVENTORY'
                WHEN p.PRODUCT_QUANTITY_AVAIL < 0.2 * COALESCE(s.QUANTITY_SOLD, 0) THEN 'LOW INVENTORY, NEED TO ADD INVENTORY'
                WHEN p.PRODUCT_QUANTITY_AVAIL < 0.6 * COALESCE(s.QUANTITY_SOLD, 0) THEN 'MEDIUM INVENTORY, NEED TO ADD SOME INVENTORY'
                ELSE 'SUFFICIENT INVENTORY'
            END
        ELSE
            CASE
                WHEN COALESCE(s.QUANTITY_SOLD, 0) = 0 THEN 'NO SALES IN PAST, GIVE DISCOUNT TO REDUCE INVENTORY'
                WHEN p.PRODUCT_QUANTITY_AVAIL < 0.3 * COALESCE(s.QUANTITY_SOLD, 0) THEN 'LOW INVENTORY, NEED TO ADD INVENTORY'
                WHEN p.PRODUCT_QUANTITY_AVAIL < 0.7 * COALESCE(s.QUANTITY_SOLD, 0) THEN 'MEDIUM INVENTORY, NEED TO ADD SOME INVENTORY'
                ELSE 'SUFFICIENT INVENTORY'
            END
    END AS INVENTORY_STATUS
FROM 
    PRODUCT p
JOIN 
    PRODUCT_CLASS pc ON p.PRODUCT_CLASS_CODE = pc.PRODUCT_CLASS_CODE
LEFT JOIN 
    (SELECT 
        PRODUCT_ID,
        SUM(PRODUCT_QUANTITY) AS QUANTITY_SOLD
     FROM 
        ORDER_ITEMS
     GROUP BY 
        PRODUCT_ID) s ON p.PRODUCT_ID = s.PRODUCT_ID
ORDER BY 
    p.PRODUCT_ID;
           
            



-- 9. WRITE A QUERY TO DISPLAY PRODUCT_ID, PRODUCT_DESC AND TOTAL QUANTITY OF PRODUCTS WHICH ARE SOLD TOGETHER WITH PRODUCT ID 201 
-- AND ARE NOT SHIPPED TO CITY BANGALORE AND NEW DELHI. DISPLAY THE OUTPUT IN DESCENDING ORDER WITH RESPECT TO TOT_QTY.(USE SUB-QUERY)
	-- [NOTE: TABLES TO BE USED -ORDER_ITEMS,PRODUCT,ORDER_HEADER, ONLINE_CUSTOMER, ADDRESS]
    
    
    SELECT 
    p.PRODUCT_ID,
    p.PRODUCT_DESC,
    SUM(oi.PRODUCT_QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM 
    ORDER_ITEMS oi
JOIN 
    ORDER_ITEMS oi2 ON oi.ORDER_ID = oi2.ORDER_ID AND oi2.PRODUCT_ID = 201
JOIN 
    ORDER_HEADER oh ON oi.ORDER_ID = oh.ORDER_ID
JOIN 
    ONLINE_CUSTOMER oc ON oh.CUSTOMER_ID = oc.CUSTOMER_ID
JOIN 
    ADDRESS a ON oc.ADDRESS_ID = a.ADDRESS_ID
JOIN 
    PRODUCT p ON oi.PRODUCT_ID = p.PRODUCT_ID
WHERE 
    oi.PRODUCT_ID <> 201
    AND a.CITY NOT IN ('Bangalore', 'New Delhi')
GROUP BY 
    p.PRODUCT_ID,
    p.PRODUCT_DESC
ORDER BY 
    TOTAL_QUANTITY_SOLD DESC;

    


-- 10. WRITE A QUERY TO DISPLAY THE ORDER_ID,CUSTOMER_ID AND CUSTOMER FULLNAME AND TOTAL QUANTITY OF PRODUCTS SHIPPED FOR ORDER IDS 
-- WHICH ARE EVENAND SHIPPED TO ADDRESS WHERE PINCODE IS NOT STARTING WITH "5" 
	-- [NOTE: TABLES TO BE USED - ONLINE_CUSTOMER,ORDER_HEADER, ORDER_ITEMS, ADDRESS]
SELECT 
    oh.ORDER_ID,
    oh.CUSTOMER_ID,
    CONCAT(oc.CUSTOMER_FNAME, ' ', oc.CUSTOMER_LNAME) AS CUSTOMER_FULLNAME,
    SUM(oi.PRODUCT_QUANTITY) AS TOTAL_QUANTITY_SHIPPED
FROM 
    order_header oh
JOIN 
    order_items oi ON oh.ORDER_ID = oi.ORDER_ID
JOIN 
    online_customer oc ON oh.CUSTOMER_ID = oc.CUSTOMER_ID
JOIN 
    address addr ON oc.ADDRESS_ID = addr.ADDRESS_ID
WHERE 
    oh.ORDER_ID % 2 = 0
    AND addr.PINCODE NOT LIKE '5%'
GROUP BY 
    oh.ORDER_ID, oh.CUSTOMER_ID, CUSTOMER_FULLNAME;

    
    
